CREATE TABLE tbl_cbt_answers(


CB_NUM	VARCHAR2(6)	NOT NULL ,
CB_NUM	VARCHAR2(6 BYTE)
CB_QUE	NVARCHAR2(125 CHAR)
CB_A1	NVARCHAR2(125)	NOT NULL    ,
CB_A2	NVARCHAR2(125)	NOT NULL	,
CB_A3	NVARCHAR2(125)	NOT NULL	,
CB_A4	NVARCHAR2(125)	NOT NULL	
CB_ANS	NUMBER		

);

SELECT * FROM tbl_cbt_answers;

CREATE TABLE tbl_cbt_answer(

CB_NUM	VARCHAR2(6)	NOT NULL ,
CB_ANS	NUMBER		

);

SELECT * FROM tbl_cbt_answers;

DROP TABLE tbl_cbt_answers;
DROP TABLE tbl_cbt_answer;
DROP TABLE tbl_cbt_questions;

CREATE TABLE tbl_cbt_Test(
CB_NUM	VARCHAR2(6) PRIMARY KEY,
CB_QUE	NVARCHAR2(125) NOT NULL,
CB_A1	NVARCHAR2(125)	NOT NULL    ,
CB_A2	NVARCHAR2(125)	NOT NULL	,
CB_A3	NVARCHAR2(125)	NOT NULL	,
CB_A4	NVARCHAR2(125)	NOT NULL	,
CB_ANS	NUMBER		NOT NULL
);

DROP TABLE tbl_cbt_Test;


CREATE TABLE tbl_cbt_Test(
CB_NUM	VARCHAR2(6) PRIMARY KEY,
CB_QUE	NVARCHAR2(125) NOT NULL,
CB_A1	NVARCHAR2(125)	NOT NULL    ,
CB_A2	NVARCHAR2(125)	NOT NULL	,
CB_A3	NVARCHAR2(125)	NOT NULL	,
CB_A4	NVARCHAR2(125)	NOT NULL	,
CB_ANS	NVARCHAR2(125) 	NOT NULL
);



