CREATE TABLE tbl_books (

B_CODE	VARCHAR2(6)	NOT NULL	PRIMARY KEY,
B_NAME	nVARCHAR2(125)	NOT NULL,	
B_AUTHER	nVARCHAR2(125)	NOT NULL	,
B_COMP	nVARCHAR2(125)		,
B_YEAR	NUMBER	NOT NULL	,
B_IPRICE	NUMBER		,
B_RPRICE	NUMBER	NOT NULL

);

SELECT COUNT(*) FROM tbl_books;

SELECT * FROM tbl_books;



CREATE TABLE tbl_users (

U_CODE	VARCHAR2(6)	NOT NULL	PRIMARY KEY,
U_NAME	nVARCHAR2(125)	NOT NULL	,
U_TEL	nVARCHAR2(125)		,
U_ADDR	nVARCHAR2(125)		

);

SELECT COUNT(*) FROM tbl_users;
SELECT * FROM tbl_users;

CREATE TABLE tbl_rent_books (
RENT_SEQ	NUMBER	NOT NULL	PRIMARY KEY,
RENT_DATE	VARCHAR2(10)	NOT NULL	,
RENT_RETURN_DATE	VARCHAR2(10)	NOT NULL,	
RENT_BCODE	VARCHAR2(6)	NOT NULL	,
RENT_UCODE	VARCHAR2(6)	NOT NULL	,
RENT_RETUR_YN	VARCHAR2(1)		,
RENT_POINT	NUMBER		
			
);


SELECT COUNT(*) FROM tbl_rent_books;


SELECT * FROM tbl_rent_books;